export const AMEEX_CITY_LIST: { id: number; name: string }[] = [
  {"id":1,"name":"Marrakech"},
  {"id":2,"name":"Meknes"},
  {"id":3,"name":"Mhaya"},
  {"id":4,"name":"Ain Taoujdate"},
  {"id":5,"name":"Sabaa Aiyoun"},
  {"id":6,"name":"Boufakrane"},
  {"id":7,"name":"El Hajeb"},
  {"id":8,"name":"Bouderbala"},
  {"id":10,"name":"Boujdour"},
  {"id":11,"name":"Tetouan"},
  {"id":12,"name":"Martil"},
  {"id":13,"name":"M Diq"},
  {"id":14,"name":"Fnideq"},
  {"id":15,"name":"Errachidia"},
  {"id":16,"name":"Oujda"},
  {"id":17,"name":"Nador"},
  {"id":18,"name":"Selouane"},
  {"id":20,"name":"Al Aaroui"},
  {"id":21,"name":"Zaio"},
  {"id":22,"name":"Driouch"},
  {"id":23,"name":"Khouribga"},
  {"id":24,"name":"Oued Zem"},
  {"id":25,"name":"Boulanouar"},
  {"id":26,"name":"Boujniba"},
  {"id":27,"name":"Bir Mezoui"},
  {"id":28,"name":"Khemisset"},
  {"id":29,"name":"Tiflet"},
  {"id":30,"name":"Mohammedia"},
  {"id":31,"name":"Ain Harrouda"},
  {"id":32,"name":"Dakhla"},
  {"id":33,"name":"Kenitra"},
  {"id":34,"name":"Sidi Taibi"},
  {"id":35,"name":"Sidi Yahya El Gharb"},
  {"id":37,"name":"Mechra Bel Ksiri"},
  {"id":38,"name":"Sidi Sliman (reg kacem)"},
  {"id":39,"name":"Sidi Kacem"},
  {"id":40,"name":"Mehdya"},
  {"id":41,"name":"Tan Tan"},
  {"id":42,"name":"Guelmim"},
  {"id":43,"name":"Bouizakarne"},
  {"id":46,"name":"Atlas Saghir ifrane"},
  {"id":47,"name":"Timoulay"},
  {"id":48,"name":"Sidi Ifni"},
  {"id":49,"name":"Rabat"},
  {"id":50,"name":"Sale"},
  {"id":51,"name":"Sale Al Jadida-سلا"},
  {"id":52,"name":"Temara"},
  {"id":53,"name":"Tamesna"},
  {"id":54,"name":"Skhirat"},
  {"id":55,"name":"Ouarzazat"},
  {"id":56,"name":"Ait Zineb"},
  {"id":57,"name":"Tabounte"},
  {"id":58,"name":"Tajda"},
  {"id":59,"name":"Timdline"},
  {"id":60,"name":"Tifoultoute"},
  {"id":61,"name":"Ifran"},
  {"id":62,"name":"Azrou(reg meknes)"},
  {"id":63,"name":"Agadir"},
  {"id":64,"name":"Inzegane"},
  {"id":65,"name":"Dcheira"},
  {"id":66,"name":"Ait Meloul"},
  {"id":67,"name":"Sidi Bibi - Agadir"},
  {"id":68,"name":"Taghazoute"},
  {"id":69,"name":"Fes"},
  {"id":70,"name":"Ain Bida"},
  {"id":71,"name":"Oulad Ettayeb"},
  {"id":72,"name":"Ain Allah"},
  {"id":73,"name":"Sidi Harazem"},
  {"id":74,"name":"Essmara"},
  {"id":75,"name":"Berrchid"},
  {"id":76,"name":"Settat"},
  {"id":77,"name":"Deroua"},
  {"id":78,"name":"Nouaceur"},
  {"id":79,"name":"Had Soualem"},
  {"id":80,"name":"Al Hoceima"},
  {"id":81,"name":"Ajdir (Région Hociema)"},
  {"id":82,"name":"Boukidaren"},
  {"id":83,"name":"Ait Kamra"},
  {"id":84,"name":"Imzouren"},
  {"id":85,"name":"Youssoufia"},
  {"id":86,"name":"Essaouira"},
  {"id":87,"name":"Ounagha"},
  {"id":88,"name":"Taftecht"},
  {"id":89,"name":"Had Draa"},
  {"id":90,"name":"Mejji"},
  {"id":91,"name":"Talmest"},
  {"id":92,"name":"Akermoud"},
  {"id":93,"name":"Zaouiet Bouzarktoune"},
  {"id":94,"name":"Ghazoua"},
  {"id":95,"name":"Smimou"},
  {"id":96,"name":"Tamanar"},
  {"id":97,"name":"Sidi Kaouki"},
  {"id":98,"name":"Tanger"},
  {"id":99,"name":"Mrirt"},
  {"id":100,"name":"Khenifra"},
  {"id":101,"name":"Ben Guerir"},
  {"id":102,"name":"Taroudannt"},
  {"id":103,"name":"Oulad Teima"},
  {"id":104,"name":"Ait Laaza"},
  {"id":105,"name":"Aoulouz"},
  {"id":107,"name":"Taliouine"},
  {"id":108,"name":"Sebt El Guerdane"},
  {"id":109,"name":"Berkane"},
  {"id":110,"name":"Saidia"},
  {"id":111,"name":"Ras El Ma (REG NADOR)"},
  {"id":112,"name":"Bni Drar"},
  {"id":113,"name":"Ahfir"},
  {"id":114,"name":"Aklim"},
  {"id":115,"name":"Zeghanghane"},
  {"id":116,"name":"Farkhana"},
  {"id":117,"name":"Taza"},
  {"id":118,"name":"Guercif"},
  {"id":119,"name":"Tiznit"},
  {"id":120,"name":"Safi"},
  {"id":121,"name":"Had Hrara"},
  {"id":122,"name":"Sebt Gzoula"},
  {"id":125,"name":"Larache"},
  {"id":126,"name":"Ksar El Kebir"},
  {"id":127,"name":"Chefchaouen"},
  {"id":128,"name":"Sidi Bernoussi"},
  {"id":129,"name":"Casablanca"},
  {"id":130,"name":"Sidi Messaoud"},
  {"id":131,"name":"Bouskoura"},
  {"id":132,"name":"Dar Bouaza"},
  {"id":133,"name":"Mediouna"},
  {"id":134,"name":"Tit Melil"},
  {"id":135,"name":"El Kelaa Des Sraghna"},
  {"id":136,"name":"El Jadida"},
  {"id":138,"name":"Sidi Bouzid"},
  {"id":140,"name":"Oualidia"},
  {"id":141,"name":"Sidi Bennour"},
  {"id":142,"name":"Beni Ansar"},
  {"id":143,"name":"Izemmouren"},
  {"id":144,"name":"Laayoune"},
  {"id":145,"name":"El Marsa"},
  {"id":146,"name":"Beni Mellal"},
  {"id":147,"name":"Fquih Ben Salah"},
  {"id":148,"name":"Sebt Oulad Nemma"},
  {"id":149,"name":"Afourer"},
  {"id":150,"name":"Ouled Yaiche"},
  {"id":151,"name":"El Ksiba"},
  {"id":152,"name":"Ain Aouda"},
  {"id":153,"name":"Tamansourt"},
  {"id":154,"name":"Benslimane ( reg mohamedia)"},
  {"id":156,"name":"Kasbah Tadla"},
  {"id":157,"name":"Chemaia"},
  {"id":160,"name":"Ourika"},
  {"id":161,"name":"Tahannaout"},
  {"id":162,"name":"Ait Ourir"},
  {"id":164,"name":"Oudaya"},
  {"id":165,"name":"Chichaoua"},
  {"id":166,"name":"Assilah"},
  {"id":167,"name":"Bouznika"},
  {"id":168,"name":"Sefrou"},
  {"id":169,"name":"Taourirt"},
  {"id":170,"name":"Chouiter"},
  {"id":171,"name":"Sidi Allal el Bahraoui"},
  {"id":172,"name":"Romani"},
  {"id":173,"name":"Oulmas"},
  {"id":174,"name":"Ouazzane"},
  {"id":175,"name":"Ain Dorij"},
  {"id":177,"name":"Sidi Redouane"},
  {"id":179,"name":"Moqrisset"},
  {"id":180,"name":"Zoumi"},
  {"id":181,"name":"Harhoura"},
  {"id":182,"name":"Laattaouia"},
  {"id":183,"name":"Rissani"},
  {"id":184,"name":"Arfoud"},
  {"id":185,"name":"Merzouga"},
  {"id":186,"name":"Taddart - TAZA -"},
  {"id":187,"name":"Bni Bouayach"},
  {"id":188,"name":"Azilal"},
  {"id":189,"name":"Ouaouizeght"},
  {"id":190,"name":"Bejaad"},
  {"id":191,"name":"Tinghir"},
  {"id":192,"name":"Boumalne Dades"},
  {"id":193,"name":"Kalaat MGouna"},
  {"id":194,"name":"Alnif"},
  {"id":195,"name":"Bou Adel"},
  {"id":196,"name":"Zrizer"},
  {"id":199,"name":"Ain Aicha"},
  {"id":200,"name":"Taounate"},
  {"id":201,"name":"Awrir"},
  {"id":202,"name":"Ait amira"},
  {"id":203,"name":"Belfaa"},
  {"id":204,"name":"Anza"},
  {"id":205,"name":"DERDARA"},
  {"id":206,"name":"Bab Taza"},
  {"id":207,"name":"AKCHOUR"},
  {"id":208,"name":"Bab berred"},
  {"id":209,"name":"El Jebeha"},
  {"id":210,"name":"Midelt"},
  {"id":211,"name":"Jerada"},
  {"id":212,"name":"Bouarfa"},
  {"id":213,"name":"Laayoun Cherqia"},
  {"id":214,"name":"Zagora"},
  {"id":215,"name":"Tamegroute"},
  {"id":216,"name":"Tagomite"},
  {"id":217,"name":"Mhamid Lghezlane"},
  {"id":218,"name":"Agdz"},
  {"id":219,"name":"Nkob"},
  {"id":220,"name":"Tazzarine"},
  {"id":221,"name":"Taghbalte"},
  {"id":222,"name":"Errich"},
  {"id":223,"name":"Missour"},
  {"id":224,"name":"Boumia"},
  {"id":225,"name":"Tinjdad"},
  {"id":226,"name":"Gulmima - errachidia"},
  {"id":227,"name":"Sidi Bouknadel"},
  {"id":228,"name":"Imintanoute"},
  {"id":229,"name":"Demnate"},
  {"id":230,"name":"Ouad Laou"},
  {"id":231,"name":"Cabo Negro"},
  {"id":232,"name":"Khmiss Zemamera"},
  {"id":234,"name":"Sidi Smail"},
  {"id":235,"name":"Oulad Fraj"},
  {"id":236,"name":"Mellalyène"},
  {"id":237,"name":"Sidi Rehal-casa"},
  {"id":238,"name":"Assa"},
  {"id":240,"name":"Rehamna"},
  {"id":241,"name":"Lakhssas"},
  {"id":242,"name":"Aoufous"},
  {"id":243,"name":"Boudnib"},
  {"id":244,"name":"Ben Ahmed - Settat -"},
  {"id":245,"name":"Sidi Bou Othmane"},
  {"id":246,"name":"Asni"},
  {"id":247,"name":"Souk Elarbaa Du Gharb"},
  {"id":248,"name":"Ajdir (Région Taza)"},
  {"id":250,"name":"Amzmiz"},
  {"id":251,"name":"Drarga"},
  {"id":253,"name":"Anza - Taddart"},
  {"id":254,"name":"Zayda"},
  {"id":255,"name":"Outat El Haj"},
  {"id":256,"name":"Tahla"},
  {"id":257,"name":"Oued Amlil"},
  {"id":258,"name":"Imouzzer Kandar"},
  {"id":260,"name":"Biogra"},
  {"id":261,"name":"Terfaya"},
  {"id":262,"name":"Tazenakht"},
  {"id":263,"name":"Figuig"},
  {"id":264,"name":"Tendrara"},
  {"id":266,"name":"Beni Tajjite"},
  {"id":267,"name":"Bouanane"},
  {"id":268,"name":"Tata"},
  {"id":270,"name":"Mzoudia"},
  {"id":271,"name":"Ksar Sghir"},
  {"id":272,"name":"Tamelelt"},
  {"id":273,"name":"El Gara"},
  {"id":274,"name":"Mirleft"},
  {"id":275,"name":"lqliaa"},
  {"id":276,"name":"oulad berhil"},
  {"id":277,"name":"zaida"},
  {"id":279,"name":"targuist"},
  {"id":280,"name":"issaguen"},
  {"id":281,"name":"tala youssef"},
  {"id":282,"name":"Jaadar"},
  {"id":283,"name":"Midar"},
  {"id":284,"name":"Ben Taieb"},
  {"id":285,"name":"Kassita"},
  {"id":286,"name":"Tafersit"},
  {"id":287,"name":"Dar El Kebdani"},
  {"id":288,"name":"Oulad Settout"},
  {"id":289,"name":"Bouarg"},
  {"id":290,"name":"Arekmane"},
  {"id":291,"name":"Krona"},
  {"id":292,"name":"Boudinar"},
  {"id":293,"name":"Tamsamane"},
  {"id":294,"name":"Annual"},
  {"id":296,"name":"BENI CHIKER"},
  {"id":297,"name":"Mariouari"},
  {"id":298,"name":"Tiztoutine"},
  {"id":299,"name":"Tamaris"},
  {"id":300,"name":"Karia Be Mohammed"},
  {"id":301,"name":"Taddart - Charaf - AGADIR"},
  {"id":302,"name":"Ben Ahmed - CHEFCHAOUEN -"},
  {"id":303,"name":"Tnine Chtouka (el jadida)"},
  {"id":304,"name":"AIN CHGAG"},
  {"id":305,"name":"Tafraoute"},
  {"id":306,"name":"Houara-oulad teima"},
  {"id":307,"name":"ERRAHMA VILLE"},
  {"id":308,"name":"azrou ait melloul"},
  {"id":309,"name":"Ben Yakhlef"},
  {"id":310,"name":"El Mansouria"},
  {"id":312,"name":"cap beddouza"},
  {"id":313,"name":"Jemâa-Shaim"},
  {"id":314,"name":"El Borouj"},
  {"id":315,"name":"oulad said settat"},
  {"id":316,"name":"sidi hajjaj (settat)"},
  {"id":317,"name":"Ras El Ain (settat)"},
  {"id":318,"name":"Guisser (settat)"},
  {"id":320,"name":"Lakhyayeta"},
  {"id":321,"name":"Nzalat Laadam"},
  {"id":322,"name":"Oulad Zidoh"},
  {"id":323,"name":"souiria Guedima (REG SAFI)"},
  {"id":324,"name":"Jorf El Melha"},
  {"id":325,"name":"Ain Beida"},
  {"id":326,"name":"Mokrisset"},
  {"id":327,"name":"Oulad Ayad"},
  {"id":329,"name":"AIN ATIQ"},
  {"id":330,"name":"Moulay Bousselham"},
  {"id":331,"name":"Khenichet"},
  {"id":332,"name":"Zoumi-Ouazzane"},
  {"id":333,"name":"Teroual - Ouazzane"},
  {"id":334,"name":"Ain Dfali-Ouazzane"},
  {"id":335,"name":"Masmouda - Ouazzane"},
  {"id":336,"name":"Stehat-Chefchaouen"},
  {"id":337,"name":"Temsia-agadir"},
  {"id":338,"name":"Tamraght"},
  {"id":339,"name":"Had bouhssoussen"},
  {"id":340,"name":"Moulay bouazza khenifra"},
  {"id":341,"name":"Tagzert"},
  {"id":342,"name":"Oulad M barek-Beni Mellal"},
  {"id":343,"name":"Tanougha-Beni Mellal"},
  {"id":344,"name":"Foum Oudi"},
  {"id":345,"name":"Ikhourbane"},
  {"id":346,"name":"Zag-VILLE"},
  {"id":347,"name":"El Ouatia"},
  {"id":348,"name":"Port of Tan-Tan"},
  {"id":349,"name":"oulad oujih"},
  {"id":350,"name":"Lalla Mimouna"},
  {"id":351,"name":"Dlalha"},
  {"id":352,"name":"Mers El Kheir"},
  {"id":353,"name":"Sidi Yahya Zaer"},
  {"id":354,"name":"Skhour Rehamna"},
  {"id":355,"name":"Amizmiz"},
  {"id":356,"name":"El Hanchane"},
  {"id":357,"name":"Akka-tata"},
  {"id":358,"name":"Tagmout-tata"},
  {"id":359,"name":"Issafen-tata"},
  {"id":360,"name":"Fam El Hisn-tata"},
  {"id":362,"name":"MASSA"},
  {"id":363,"name":"Kariat Arkman-Nador"},
  {"id":364,"name":"Had Hrara-SAFI"},
  {"id":365,"name":"Sidi Zouine"},
  {"id":366,"name":"Skoura-Ouarzazate"},
  {"id":367,"name":"Bni hdifa - Region Al hoceima"},
  {"id":368,"name":"Bab Marzouka-Taza"},
  {"id":369,"name":"Aknoul-taza"},
  {"id":370,"name":"Hattane-Khouribga"},
  {"id":371,"name":"sidi allal tazi"},
  {"id":372,"name":"Tiddas"},
  {"id":373,"name":"Ain Johra"},
  {"id":374,"name":"Maâziz"},
  {"id":376,"name":"Tīdās-Khemisset"},
  {"id":377,"name":"Laouamra- ksar el kebir"},
  {"id":378,"name":"Khemis Sahel"},
  {"id":379,"name":"Krimda"},
  {"id":380,"name":"Sidi Aissa-Beni-Mellal"},
  {"id":381,"name":"Ouled Moussa-Beni Mellal"},
  {"id":382,"name":"Oulad Said-Beni Mellal"},
  {"id":383,"name":"ighram laalam-beni mellal"},
  {"id":384,"name":"Tanougha-Beni Mellal"},
  {"id":385,"name":"Zaouiat Cheikh"},
  {"id":386,"name":"Ait Ali"},
  {"id":387,"name":"Lehri-KHENIFRA"},
  {"id":388,"name":"El Kebab-KHENIFRA"},
  {"id":389,"name":"El Borj-KHENIFRA"},
  {"id":391,"name":"Ouaoumana"},
  {"id":392,"name":"Ait ishaq"},
  {"id":394,"name":"Tighassaline ville"},
  {"id":395,"name":"Aguelmous"},
  {"id":397,"name":"Bounouar"},
  {"id":398,"name":"HATTANE"},
  {"id":399,"name":"Boujniba"},
  {"id":400,"name":"Ouaouizeght"},
  {"id":401,"name":"Adouz"},
  {"id":402,"name":"Foum El Anceur"},
  {"id":403,"name":"FERYATA"},
  {"id":404,"name":"Foum Zaouia"},
  {"id":405,"name":"Tanougha-Beni Mellal"},
  {"id":406,"name":"Al kamoun-ksba tadla"},
  {"id":407,"name":"Jerf El Melha"},
  {"id":408,"name":"Zemamra"},
  {"id":410,"name":"Sidi Smail"},
  {"id":411,"name":"Azemmour"},
  {"id":412,"name":"Bir Jdid"},
  {"id":413,"name":"El Jorf Lasfar"},
  {"id":414,"name":"Moulay Abdallah Amghar"},
  {"id":415,"name":"El Aouamra"},
  {"id":416,"name":"Laarache"},
  {"id":417,"name":"Oulad Bourahma"},
  {"id":418,"name":"Zone Franche (kenitra)"},
  {"id":420,"name":"Ghafsai"},
  {"id":421,"name":"sidi aadi"},
  {"id":422,"name":"Mejjat-chichaoua"},
  {"id":423,"name":"Ain Tekki"},
  {"id":426,"name":"OULAD ABBOU-settat"},
  {"id":428,"name":"AIN LEUH"},
  {"id":429,"name":"Souihla"},
  {"id":430,"name":"El Haj Kaddour"},
  {"id":431,"name":"Boulemane"},
  {"id":432,"name":"Tin Mansour"},
  {"id":433,"name":"Arba Aounate"},
  {"id":434,"name":"AIN BNI MATHAR"},
  {"id":435,"name":"Tikiouine"},
  {"id":437,"name":"Chellalat Mohammedia"},
  {"id":438,"name":"Zouada"},
  {"id":439,"name":"Arbaoua"},
  {"id":440,"name":"Sidi el Aidi"},
  {"id":443,"name":"DAR GUEDDARI"},
  {"id":445,"name":"Tagadirt-Agadir"},
  {"id":446,"name":"Tadouaret-Agadir"},
  {"id":447,"name":"Leqliaa - Taddart"},
  {"id":448,"name":"ain mediouna - taounate"},
  {"id":449,"name":"ain aicha - taounate"},
  {"id":450,"name":"zrizer - taounate"},
  {"id":451,"name":"Ain Sbit"},
  {"id":452,"name":"MERCHOUCH"},
  {"id":453,"name":"TANANTE-AZILAL"},
  {"id":454,"name":"Birkouate"},
  {"id":455,"name":"Moulay Yaâcoub"},
  {"id":456,"name":"sidi boujida"},
  {"id":457,"name":"Oulad Tayeb"},
  {"id":458,"name":"Ain Chkef"},
  {"id":459,"name":"Ouled Khlifa"},
  {"id":460,"name":"LOUDAYA"},
  {"id":461,"name":"Tassoultante"},
  {"id":463,"name":"Tameslouht"},
  {"id":464,"name":"Sidi Moussa-OURIKA"},
  {"id":465,"name":"Gueznaia - Tanger"},
  {"id":466,"name":"TANGER-bougdour"},
  {"id":467,"name":"AIN DALIA-tanger"},
  {"id":468,"name":"Chraka - Tanger"},
  {"id":469,"name":"TANGER-chaouia"},
  {"id":471,"name":"tamchat"},
  {"id":472,"name":"TAGANTE"},
  {"id":473,"name":"Moulay Idriss Zerhoun"},
  {"id":476,"name":"BOUYAFAR"},
  {"id":477,"name":"Sidi Bousberr"},
  {"id":478,"name":"LAMJAARA-ouazzane"},
  {"id":480,"name":"BRIKCHA-ouazzane"},
  {"id":481,"name":"Beni Quolla-ouazzane"},
  {"id":482,"name":"Mzefroune-ouazzane"},
  {"id":484,"name":"Sidi Elmoukhtar - Chichaoua"},
  {"id":485,"name":"Ouled El Ghadbane"},
  {"id":487,"name":"Had kourt"},
  {"id":488,"name":"Madagh-berkan"},
  {"id":489,"name":"Laatamna"},
  {"id":490,"name":"Sebt ben sassi"},
  {"id":491,"name":"AIT BAHA"},
  {"id":493,"name":"Ribate El Kheir-sefrou"},
  {"id":494,"name":"El Menzale-sefrou"},
  {"id":495,"name":"Tizi Ouasli"},
  {"id":496,"name":"MSOUN taza"},
  {"id":499,"name":"Akhfennir"},
  {"id":500,"name":"Gfifat-oulad teima"},
  {"id":501,"name":"Oulad Dahou-HOUARA"},
  {"id":502,"name":"TIMAHDITE-AZROU"},
  {"id":503,"name":"AGOURAY"},
  {"id":504,"name":"SIDI AADI"},
  {"id":505,"name":"Lalla Takerkoust"},
  {"id":506,"name":"Oulad yahya-Marrakech"},
  {"id":507,"name":"Chrifia-Marrakech"},
  {"id":508,"name":"Sidi Abdellah Ghiat"},
  {"id":509,"name":"Ait Ben Haddou"},
  {"id":510,"name":"TALSINNT"},
  {"id":511,"name":"Aouama-Tanger"},
  {"id":512,"name":"Ras El Ain Rehamena- Tamelelt"},
  {"id":513,"name":"Tlauh - Tamelelt"},
  {"id":514,"name":"EL AIOUN SIDI MELLOUK"},
  {"id":515,"name":"Bir Tam Tam"},
  {"id":516,"name":"Ras Tabouda"},
  {"id":517,"name":"Zaouia Bougrine"},
  {"id":518,"name":"El houmer-taroudant"},
  {"id":519,"name":"Oulad Terna"},
  {"id":520,"name":"Ouled Abbou-TAROUDANT"},
  {"id":521,"name":"Oulad Aissa-TAROUDANT"},
  {"id":522,"name":"Tazemmourt-taroudant"},
  {"id":523,"name":"tamaloukt-taroudant"},
  {"id":524,"name":"nouail-taroudant"},
  {"id":525,"name":"oulad mhela-taroudant"},
  {"id":526,"name":"El boura-taroudant"},
  {"id":527,"name":"Oulad brahim-taroudant"},
  {"id":528,"name":"Sidi moussa lhamri-TAROUDANT"},
  {"id":529,"name":"Ahmar laglalcha-taroudant"},
  {"id":530,"name":"IGHREM-TATA"},
  {"id":531,"name":"ASJENN-ouazzane"},
  {"id":532,"name":"TAFOUGHALT"},
  {"id":533,"name":"AIN SFA-OUJDA"},
  {"id":534,"name":"Bouhouda-taounat"},
  {"id":535,"name":"Tahar Souk-taounat"},
  {"id":536,"name":"bouaadl-taounat"},
  {"id":537,"name":"Ouled azem-taounat"},
  {"id":538,"name":"Tazouda-taounat"},
  {"id":539,"name":"Timezgana-taounat"},
  {"id":540,"name":"Imouzzer Marmoucha"},
  {"id":541,"name":"MEZRAOUA-taounat"},
  {"id":542,"name":"Ait Yaazem-meknes"},
  {"id":544,"name":"Ourtzagh-taounat"},
  {"id":545,"name":"Kasbat ayir-oualidia"},
  {"id":546,"name":"Amerzgane"},
  {"id":547,"name":"Imini-Ouarzazate"},
  {"id":550,"name":"LAMHIRIZ-dakhla"},
  {"id":552,"name":"AIN SMEN-FES"},
  {"id":553,"name":"Idouirane-Imintanuot"},
  {"id":554,"name":"Tamait Izder-agadir"},
  {"id":555,"name":"Tinzouline-zagora"},
  {"id":557,"name":"BEN ZOLI"},
  {"id":558,"name":"Tagounite"},
  {"id":559,"name":"Ain el Mediour- taroudant"},
  {"id":560,"name":"Ouled Mssaad"},
  {"id":561,"name":"Oulad Othmane"},
  {"id":562,"name":"Oulad Yahya Lagraire"},
  {"id":563,"name":"Tinnegza"},
  {"id":564,"name":"Ouled Moqaddem"},
  {"id":565,"name":"Aït Attab"},
  {"id":566,"name":"Oulad Aissa- el jadida"},
  {"id":567,"name":"BRADIA"},
  {"id":568,"name":"Souk El Had Des Bradia"},
  {"id":570,"name":"Ouzoud"},
  {"id":571,"name":"HOUARA-Tanger"},
  {"id":572,"name":"MEHARZA-Tanger"},
  {"id":573,"name":"EL MNBAR-Tanger"},
  {"id":574,"name":"AIN BELLOUT-Tanger"},
  {"id":575,"name":"Agouim"},
  {"id":576,"name":"Ighrem N Ougdal"},
  {"id":577,"name":"Tarmigt"},
  {"id":578,"name":"Ain jiri"},
  {"id":579,"name":"Tlata Loulad Fini"},
  {"id":580,"name":"Tnine Beni Meskine"},
  {"id":581,"name":"Aghbalou N serdan"},
  {"id":582,"name":"Itzer-zaida"},
  {"id":583,"name":"Zoualeth Dkhissa"},
]

export const AMEEX_CITY_MAP: Record<string, number> = Object.fromEntries(
  AMEEX_CITY_LIST.map(c => [c.name.toLowerCase(), c.id])
)

export function getAmeexCityId(cityName: string): number | null {
  const key = cityName.toLowerCase().trim()
  return AMEEX_CITY_MAP[key] ?? null
}
